[package]
name = "rust-book"
version = "0.1.0"
authors = ["Martin Junghanns <martin.junghanns@neo4j.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
