// chapter 3
pub mod common_programming_concepts;
// chapter 4
pub mod ownership;
// chapter 5
pub mod structs;
// chapter 6
pub mod enums;
// chapter 8
pub mod collections;
// chapter 9
pub mod error_handling;
// chapter 10
pub mod generics;
// chapter 13
pub mod iterators_closures;
// chapter 15
pub mod smart_pointers;
